### ISSUE TITLE
Semester selection results incongruent with input

### ISSUE THREAD

**Issue by sthukral** [nisstyre56/TextbookEngine#2]
When I search for the winter term, I see results in the fall term:

![image](https://cloud.githubusercontent.com/assets/13511336/17502768/b8075fce-5db8-11e6-8f59-6e2c9a17b346.png)

**Comment by nisstyre56** [comment]
Fixed in the latest version, it now correctly matches the semester fields

**Comment by weskerfoot** [comment]
Fixed in the latest version, it now correctly matches the semester fields

**Comment by sthukral** [comment]
No it doesn't.

See here:

![image](https://cloud.githubusercontent.com/assets/13511336/17518154/aac2e688-5e14-11e6-808b-b10a9a1bcebc.png)
